services:
  db:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coinwatch
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    networks:
      - coinwatch_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "user", "--password=password"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '8080:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - coinwatch_network

  app:
    build:
      context: .
    container_name: coinwatch
    tty: true
    command: ["python", "-m", "src.main"]
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - coinwatch_network
    environment:
      PYTHONPATH: /app
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: coinwatch
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: DEBUG

  # test:
  #   build:
  #     context: .
  #   container_name: coinwatch_test
  #   tty: true
  #   command: /bin/sh -c "PYTHONPATH=/app python -m src.tests.test_connections && PYTHONPATH=/app python -m src.tests.test_data_collection"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     app:
  #       condition: service_started
  #   networks:
  #     - coinwatch_network
  #   environment:
  #     PYTHONPATH: /app
  #     DB_HOST: db
  #     DB_USER: user
  #     DB_PASSWORD: password
  #     DB_NAME: coinwatch


volumes:
  data:

networks:
  coinwatch_network: