services:
  db:
    image: mysql:8.4
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coinwatch_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3307:3306"
    networks:
      - coinwatch_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "test_user", "--password=test_password"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '8080:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - coinwatch_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coinwatch_test_app
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - coinwatch_network
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - DB_NAME=coinwatch_test
      - BYBIT_TESTNET=true
      - LOG_LEVEL=DEBUG
    command: python -m src.test_main

networks:
  coinwatch_network:
    name: coinwatch_test_network

volumes:
  logs: