services:
  db:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coinwatch
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    networks:
      - coinwatch_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - coinwatch_network

  app:
    build:
      context: .
    container_name: coinwatch
    tty: true
    command: ["python", "src/main.py"]
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - coinwatch_network
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: coinwatch

volumes:
  data:

networks:
  coinwatch_network:
